name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v2
      - run: chmod +x gradlew
      - run: ./gradlew deploy
      - uses: actions/upload-artifact@v3
        with:
          name: dark-afflict-mod
          path: build/libs/dark-afflict.jar
